### ISSUE TITLE
Unrecoverable cycle resolving import error

### ISSUE THREAD

**Issue by reactivemaster** [strongtyped/active-slick#71] opened 2015-10-20 16:23 UTC
Hello.
I tried to use active-slick in my project but I got a weird problem.
For example, I have model class (MyModel.scala):
```scala
package models

case class MyModel(name: String, id: Option[Int] = None)
```

DAO class (MyModelDAO.scala), where I import and use "MyModel":
```scala
package dao

import play.api.libs.concurrent.Execution.Implicits.defaultContext

import slick.driver.JdbcProfile
import slick.backend.DatabaseConfig
import slick.ast.BaseTypedType
import io.strongtyped.active.slick._
import io.strongtyped.active.slick.Lens._

import models.MyModel

class MyModelDAO extends EntityActions with JdbcProfileProvider {
  val dc = DatabaseConfig.forConfig[JdbcProfile]("mydb")
  type JP = JdbcProfile
  val jdbcProfile = dc.driver
  val db = dc.db

  import jdbcProfile.api._
  val baseTypedType = implicitly[BaseTypedType[Id]]

  type Entity = MyModel
  type Id = Int
  type EntityTable = MyModelTable

  val tableQuery = TableQuery[MyModelTable]

  def $id(table: MyModelTable): Rep[Int] = table.id

  val idLens = lens { model: MyModel => model.id  }
                    { (model, id) => model.copy(id = id) }

  class MyModelTable(tag: Tag) extends Table[MyModel](tag, "models") {
    def id = column[Int]("id", O.PrimaryKey, O.AutoInc)
    def name = column[String]("name")
    def * = (name, Rep.Some(id)) <> ((MyModel.apply _).tupled, MyModel.unapply)
  }

  def findByName(name:String): DBIO[Seq[MyModel]] = {
    tableQuery.filter(_.name === name).result
  }

  def run[R](dbioAction: DBIOAction[R, NoStream, Nothing]) = db.run(dbioAction)
}
```

And my example controller action where I use DAO class:
```scala
package controllers

...
import dao.MyModelDAO
...

class Application extends Controller {

  def index = Action.async {
    val myModelDAO = new MyModelDAO
    val action = myModelDAO.findByName("name1")

    myModelDAO.run(action).map(res => {
      // res processing
      Ok("ok")
    })
  }

  ...

}
```

Then when I try to compile my project, I get such errors in console:
> MyModelDAO.scala:19: encountered unrecoverable cycle resolving import.
>  Note: this is often due in part to a class depending on a definition nested within its companion.
>  If applicable, you may wish to try moving some members into another object.
>  import jdbcProfile.api._
>                              ^

> MyModelDAO.scala:20: ambiguous implicit values:
>   both method booleanColumnType in trait ImplicitColumnTypes of type => MyModelDAO.this.jdbcProfile.columnTypes.BooleanJdbcType
>   and method blobColumnType in trait ImplicitColumnTypes of type => MyModelDAO.this.jdbcProfile.columnTypes.BlobJdbcType
>  val baseTypedType = implicitly[BaseTypedType[Id]]
>                                                  ^

> MyModelDAO.scala:36: No matching Shape found.
>  Slick does not know how to map the given types.
>  Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).

What's wrong with my code?
When I use a pure slick or play-slick, I never get such errors.

P.S. To ensure this error you can clone my small example project (https://github.com/reactivemaster/active-slick-example) and run **"sbt compile"** in it.

**Comment by rcavalcanti** [comment] 2015-10-21 15:39
Hi @reactivemaster,

Thanks for sending an example that I can use to investigate.

I will try to have a look into it as soon as possible.

**Comment by rcavalcanti** [comment] 2015-10-21 15:47
Gave it a quick look.

try this:
```scala
  type JP = slick.driver.MySQLDriver
  val jdbcProfile = slick.driver.MySQLDriver
```

I think the driver you are getting from `dc.driver` is not the right one.

If you need to use different drivers, it's better to use the cake pattern. 
You can find an example implementation here:
https://github.com/phancox/active-slick-dynamic-provider/pull/1

**Comment by reactivemaster** [comment] 2015-10-21 16:08
@rcavalcanti, I relied on the code of this class when I wrote my DAO class: https://github.com/rcavalcanti/active-slick-dynamic-provider/blob/master/src/main/scala/com/dtc/deltasoft/entity/ConfiguredProfileProvider.scala#L22

**Comment by rcavalcanti** [comment] 2015-10-21 19:06
Hi @reactivemaster, I didn't look further, but there must exist a difference between your code and the example from active-slick-dynamic-provider because the latter works.

Let me know what are your finds so we can close this issue

**Comment by reactivemaster** [comment] 2015-10-21 22:41
@rcavalcanti, I'm not sure exactly what the reason, but I did some experiments and found that if I take out driver configuration (first 4 lines of MyModelDAO class) in a separate trait (as you can see in this commit https://github.com/reactivemaster/active-slick-example/commit/acf0f305d4970be1815ae81083095ebcebb01690), then code compiles successfully.
But in this case I don't fully understand - why should I prefer to use a cake pattern, as you wrote above, instead of configuring the driver on the fly?
Can you explain it in a few words, please?

**Comment by dholbrook** [comment] 2015-10-26 17:25
@rcavalcanti 

I also like to defer the driver implantation until object creation time, that allows me to write fast integration tests against H2, and have the production code go against a "real" database.

I think the problem is the JP type definition in the JdbcProfileProvider.  I was able to get it to work like so:

```scala
package com.example.task.dao

import io.strongtyped.active.slick.Lens._
import io.strongtyped.active.slick.{EntityActions, JdbcProfileProvider}
import slick.ast.BaseTypedType
import slick.driver.JdbcProfile

case class Task(description: String,  complete: Boolean, id: Option[Long])

class TaskDao(override val jdbcProfile: JdbcProfile) extends EntityActions with JdbcProfileProvider {

  override type JP = JdbcProfile
  import jdbcProfile.api._

  override type Entity = Task
  override type Id = Long
  override type EntityTable = TaskTable

  override val baseTypedType = implicitly[BaseTypedType[Id]]
  override val tableQuery = TableQuery[EntityTable]
  override val idLens = lens { task: Task => task.id } { (task, id) => task.copy(id = id) }

  override def $id(table: TaskTable): Rep[Id] = table.id

  class TaskTable(tag: Tag) extends Table[Task](tag, "task") {
    def description = column[String]("description")
    def complete = column[Boolean]("complete")
    def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
    def * = (description, complete, id.?) <>(Task.tupled, Task.unapply)
  }

}
```

**Closed** 2016-05-20 08:17 UTC
